---
- name: "SG350 | Créer les VLANs"
  cisco.ios.ios_vlans:
    config:
      - vlan_id: "{{ item.id }}"
        name: "{{ item.name }}"
        state: active
    state: merged
  loop: "{{ vlans }}"

- name: "SG350 | Configurer ports uplink vers FortiGate"
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ item.interface }}"
        mode: access
        access:
          vlan: "{{ item.vlan }}"
    state: merged
  loop: "{{ uplink_ports }}"

- name: "SG350 | Configurer ports access clients"
  cisco.ios.ios_config:
    lines:
      - description {{ item.description }}
      - switchport mode access
      - switchport access vlan {{ item.vlan }}
      - spanning-tree portfast
      - no shutdown
    parents: "interface {{ item.interface }}"
  loop: "{{ access_ports }}"

- name: "SG350 | Sauvegarder"
  cisco.ios.ios_config:
    save_when: always
