---
all:
  children:
    fortigate:
      hosts:
        fortigate60e:
          ansible_host: 192.168.99.99
          ansible_user: admin
          ansible_network_os: fortinet.fortios.fortios
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false

    sg350:
      hosts:
        cisco_sg350:
          ansible_host: 192.168.99.254
          ansible_user: admin
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
          ansible_become: true
          ansible_become_method: enable
